haystack:
  kafka:
  # TODO write value from $(minikube ip) to a file and use that file here instead of hardcoding in the next line
      brokers: "192.168.99.101" # local minikube value, typically .100 or .101, to be overridden by env variable
      port: 9092 # default Kafka port, rarely overridden, but can be overridden by env variable